import { readFile, writeFile } from "node:fs/promises";

const BUILD_ORDER = [
  "shared/run-result.js",
  "src/config.js",
  "src/leaderboard.js",
  "src/ui.js",
  "src/game.js",
  "src/main.js"
];

const root = new URL("../", import.meta.url);

async function build() {
  const modules = await Promise.all(
    BUILD_ORDER.map((file) => readFile(new URL(file, root), "utf8"))
  );

  let code = modules.join("\n\n");
  code = code.replace(/^\s*import[\s\S]*?;\r?\n/gm, "");
  code = code.replace(/^export\s+/gm, "");

  const output = `// Generated by scripts/build-app.mjs. Edit source files under shared/ and src/.\n(function () {\n${code}\n})();\n`;
  await writeFile(new URL("app.js", root), output, "utf8");
}

build().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
